apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: env-service-base

# Namespace is NOT included here - each tenant creates its own
resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: env-service
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false
