apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tenant-b-staging

resources:
  - namespace.yaml
  - ../../../stages/staging

labels:
  - pairs:
      tenant: tenant-b
      environment: staging
    includeSelectors: false

patches:
  - path: configmap-patch.yaml

images:
  - name: andycpx/kargodemo
    newName: andycpx/kargodemo
    newTag: v1.0.0
