apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tenant-a-dev
resources:
- namespace.yaml
- ../../../stages/dev
labels:
- pairs:
    tenant: tenant-a
    environment: dev
  includeSelectors: false
patches:
- path: configmap-patch.yaml
images:
- name: andycpx/kargodemo
  newName: andycpx/kargodemo
  newTag: dev
- name: docker.io/andycpx/kargodemo
  newTag: dev-20260122
