apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: env-service
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - tenant: tenant-a
                - tenant: tenant-b
          - list:
              elements:
                - stage: dev
                  autoSync: "true"
                - stage: staging
                  autoSync: "false"
                - stage: prod
                  autoSync: "false"
  template:
    metadata:
      name: "env-service-{{tenant}}-{{stage}}"
      labels:
        app: env-service
        tenant: "{{tenant}}"
        stage: "{{stage}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/AndyCpX/argo-argocd-gitops-demo.git
        targetRevision: HEAD
        path: "gitops/tenants/{{tenant}}/{{stage}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{tenant}}-{{stage}}"
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
  templatePatch: |
    {{- if eq .autoSync "true" }}
    spec:
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
    {{- end }}
